" Plugins
execute pathogen#infect()
set nocompatible
filetype off

filetype plugin indent on
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching=0


" End of Plugins

" Set a color_scheme
syntax on
colorscheme onehalfdark

" Beginning of line is zero`
nmap 0 ^
nmap k gk
nmap j gj

" Set this as soon as possible
let mapleader ="\<Space>"

nmap <leader>pi :PluginInstall<cr>
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

nmap <leader>w :w<cr>
nmap <leader>qqq :q<cr>

imap jk <esc>
imap kj <esc>
" Save all
imap <C-a> <esc>:w<cr>
set number

set tabstop=2
set softtabstop=2
set expandtab

autocmd Filetype help nmap <buffer> q :q<cr>

autocmd VimResized * :wincmd =
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

let g:VtrUseVtrMaps = 1
nnoremap <leader>irb :VtrSendCommandToRunner irb<cr>
"nnoremap <leader>: :VtrSendCommandToRunner rspec<cr>
nnoremap <leader>t :VtrSendCommandToRunner rails test<cr>
nnoremap <leader>pry :VtrSendCommandToRunner pry<cr>
nnoremap <leader>rr :VtrSendCommandToRunner rails routes<cr>
nnoremap <leader>xit :VtrSendCommandToRunner exit<cr>
nnoremap <leader>cd :VtrSendCtrlD<cr>
noremap <c-f> :VtrSendLinesToRunner<cr>
