filetype plugin indent on
if executable('rg')
  let g:ctrlp_user_command = 'rg %s --files --hidden --color=never --glob ""'
else
  if executable('ag')
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""''
  endif
endif

let g:ctrlp_show_hidden = 1

execute pathogen#infect()
" Set a color_scheme
colorscheme atom

syntax on

" Beginning of line is zero`
nmap 0 ^
nmap k gk
nmap j gj

" Set this as soon as possible
let mapleader ="\<Space>"

let g:javascript_plugin_flow = 1
let g:jsx_ext_required = 0

let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0

nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

nmap <leader>w :w<cr>
nmap <leader>qqq :q<cr>

imap jk <esc>
imap kj <esc>
" Save all
imap <C-a> <esc>:w<cr>
set number

set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set textwidth=80
set autoindent

autocmd Filetype help nmap <buffer> q :q<cr>

autocmd VimResized * :wincmd =
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

let g:VtrUseVtrMaps = 1
nnoremap <leader>irb :VtrSendCommandToRunner irb<cr>
nnoremap <leader>pry :VtrSendCommandToRunner pry<cr>
nnoremap <leader>rr :VtrSendCommandToRunner rails routes<cr>
nnoremap <leader>xit :VtrSendCommandToRunner exit<cr>
nnoremap <leader>cd :VtrSendCtrlD<cr>
noremap <Leader>sl :VtrSendLinesToRunner<cr>
nnoremap <Leader>cs :colorscheme<space>

map <Leader>t :call RunCurrentSpecFile()<CR>
map <leader>s :call RunNearestSpec()<CR>
map <leader>l :call RunLastSpec()<CR>
map <leader>a :call RunAllSpecs()<CR>
